### ISSUE TITLE
[PE-D] Invalid UG example

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-W13-2/tp#131]
The user guide provide an invalid example

![image.png](https://raw.githubusercontent.com/lowkaiwei98/ped/main/files/3a202c48-f1ce-41ee-8f74-e8a86cb29a00.png)

Steps to reproduce:
1. copy the UG example
2. paste on the CLI input
3. hit enter

Expected:
example to work

Actual:
Invalid command format! 
 
![image.png](https://raw.githubusercontent.com/lowkaiwei98/ped/main/files/8fe1ef44-2b71-45ea-b190-1fe776fed73e.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: lowkaiwei98/ped#1

**Comment by honganhcs** [comment]
similar to #134
