### ISSUE TITLE
[PE-D] Cannot edit tutorial group wrong error message 

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-W13-2/tp#155]
![image.png](https://raw.githubusercontent.com/hqhqhq1/ped/main/files/dc680f62-0f30-48db-a957-5d7de64f64e0.png)
Cannot edit tutorial group wrong error message 

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: hqhqhq1/ped#6

**Comment by seanlaiys** [comment]
edit is meant for person or student, have made clearer in User Guide.
