### ISSUE TITLE
[PE-D] Typo in message usage for grade command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-W13-2/tp#165]
![2022-04-01_15-02.png](https://raw.githubusercontent.com/Graphcalibur/ped/master/files/aa047c82-3d4e-4ec8-9c1d-a49d96492942.png)

See the "%d" at the end.

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: Graphcalibur/ped#11

**Comment by honganhcs** [comment]
similar to #180, fixed
