### ISSUE TITLE
[PE-D] list_attendance minor feature flaw

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-W13-2/tp#167]
list_attendance also only provides the student ID without the name of the student, might be useful to have included name for TA.

![Screenshot 2022-04-01 at 3.03.21 PM.png](https://raw.githubusercontent.com/rcjj98/ped/main/files/66a7f487-6609-476f-9c2d-f06161ec2c39.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: rcjj98/ped#6

**Comment by kev-intq** [comment]
Will change this to use student name
