### ISSUE TITLE
[PE-D] Not intuitive to use

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-W13-2/tp#189]
The parameters keep switching around from name to student id. Not intuitive to use this program as there are too many commands with varying parameters

For example:

comment need student id:

![image.png](https://raw.githubusercontent.com/lowkaiwei98/ped/main/files/d182e825-4dd1-4034-a14a-38b16d26ccb0.png)

While grading need student name:

![image.png](https://raw.githubusercontent.com/lowkaiwei98/ped/main/files/d808922e-7ce5-4a94-8cfd-b57f72453c96.png)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: lowkaiwei98/ped#12

**Comment by seanlaiys** [comment]
As we cannot change method signature in v1.4, we will not be doing anything here. However, where there is reference to the existing user ID of a particular student, using NusNetId may be preferred by some users as there are lesser things to type
